name: Test
on:
  pull_request:
jobs:
  test-gofmt:
    name: runner / suggester / gofmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: gofmt -w -s .
      - uses: ./
        with:
          tool_name: gofmt

  test-shfmt:
    name: runner / suggester / shfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: GO111MODULE=on go get mvdan.cc/sh/v3/cmd/shfmt && go install mvdan.cc/sh/v3/cmd/shfmt
      - run: echo $PATH
      - run: ls $GOBIN
      - run: ls $GOPATH/bin
      - run: ls $(go env GOPATH)/bin
      - run: shfmt -i 2 -ci -w .
      - uses: ./
        with:
          tool_name: shfmt
